name: Run Regression Tests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Test Group to Run'
        required: false
        default: 'collections'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ALLURE_RESULTS_DIR: target/allure-results

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run API Tests
        run: mvn clean test || true

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: allure-gh-pages
          path: allure-gh-pages

      - name: Create Allure report for GH Pages
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
          gh_pages: allure-gh-pages
          allure_history: allure-history
          allure_results: target/allure-results
          keep_reports: 20

      - name: Deploy Allure report to GH Pages
        uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.PAT }}
          PUBLISH_BRANCH: allure-gh-pages
          PUBLISH_DIR: allure-history

      - name: Print Allure Report URL
        if: always()
        run:
          echo "Allure report https://liudmilaparf.github.io/rijksmuseum-api-tests/"
